export type SelectOption = { value: string; label: string; labelSw?: string };

type BaseField = {
  name: string;
  label: string;
  labelSw?: string;
  help?: string;
  helpSw?: string;
  /** Only rendered/submitted when another field currently equals this value. */
  showIf?: { field: string; equals: string };
};

export type OptionField =
  | (BaseField & { type: "select"; options: SelectOption[]; defaultValue?: string })
  | (BaseField & { type: "number"; defaultValue?: number; min?: number; max?: number; step?: number })
  | (BaseField & { type: "text"; placeholder?: string; placeholderSw?: string; defaultValue?: string })
  | (BaseField & { type: "password"; placeholder?: string; placeholderSw?: string })
  | (BaseField & { type: "checkbox"; defaultValue?: boolean })
  | (BaseField & { type: "page-range"; placeholder?: string; placeholderSw?: string })
  | (BaseField & { type: "page-picker"; pickerMode: "select" | "ranges" })
  | (BaseField & { type: "textarea"; placeholder?: string; placeholderSw?: string; defaultValue?: string });

export type SecondaryFile = {
  name: string;
  label: string;
  labelSw?: string;
  accept: string;
  showIf?: { field: string; equals: string };
};

export type ToolDefinition = {
  slug: string;
  endpoint: string;
  requiresFile: boolean;
  fileFieldName: string;
  multiple: boolean;
  accept: string;
  minFiles: number;
  fields: OptionField[];
  secondaryFile?: SecondaryFile;
  resultKind: "file" | "zip";
  resultFilename: string;
  submitLabel?: string;
  submitLabelSw?: string;
  helperNote?: string;
  helperNoteSw?: string;
  /** "workspace" renders the side-by-side live-preview + controls layout
   * (WorkspaceToolPage) instead of the default single-column form (GenericToolPage).
   * Piloted on a few tools before wider rollout -- omit for the standard layout. */
  layout?: "workspace";
};

const PDF_ACCEPT = ".pdf,application/pdf";

const PAGE_RANGE_HELP = "e.g. \"1-3, 5, 8-10\" (leave blank for all pages where applicable)";
const PAGE_RANGE_HELP_SW = "mfano \"1-3, 5, 8-10\" (acha wazi kwa kurasa zote inapowezekana)";
const LEAVE_BLANK_ALL = "leave blank for all";
const LEAVE_BLANK_ALL_SW = "acha wazi kwa zote";

export const TOOL_DEFINITIONS: Record<string, ToolDefinition> = {
  "split-pdf": {
    slug: "split-pdf",
    endpoint: "/api/v1/organize/split",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "mode",
        label: "Split mode",
        labelSw: "Aina ya kugawanya",
        defaultValue: "ranges",
        options: [
          { value: "ranges", label: "Custom page ranges", labelSw: "Wigo maalum wa kurasa" },
          { value: "burst", label: "Every page as its own file", labelSw: "Kila ukurasa kama faili lake" },
          { value: "interval", label: "Fixed interval", labelSw: "Muda maalum kati ya kurasa" },
        ],
      },
      {
        type: "page-picker",
        pickerMode: "ranges",
        name: "ranges",
        label: "Click pages to build each output file",
        labelSw: "Bofya kurasa kujenga kila faili la matokeo",
        showIf: { field: "mode", equals: "ranges" },
      },
      {
        type: "number",
        name: "interval",
        label: "Pages per file",
        labelSw: "Kurasa kwa kila faili",
        defaultValue: 5,
        min: 1,
        showIf: { field: "mode", equals: "interval" },
      },
    ],
    resultKind: "zip",
    resultFilename: "split_pages.zip",
    submitLabel: "Split PDF",
    submitLabelSw: "Gawanya PDF",
    layout: "workspace",
  },
  "remove-pages": {
    slug: "remove-pages",
    endpoint: "/api/v1/organize/remove-pages",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "page-picker",
        pickerMode: "select",
        name: "pages",
        label: "Click the pages to remove",
        labelSw: "Bofya kurasa za kuondoa",
      },
    ],
    resultKind: "file",
    resultFilename: "pages_removed.pdf",
    submitLabel: "Remove pages",
    submitLabelSw: "Ondoa kurasa",
    layout: "workspace",
  },
  "extract-pages": {
    slug: "extract-pages",
    endpoint: "/api/v1/organize/extract-pages",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "page-picker",
        pickerMode: "select",
        name: "pages",
        label: "Click the pages to extract",
        labelSw: "Bofya kurasa za kutoa",
      },
    ],
    resultKind: "file",
    resultFilename: "extracted_pages.pdf",
    submitLabel: "Extract pages",
    submitLabelSw: "Toa kurasa",
    layout: "workspace",
  },
  "compress-pdf": {
    slug: "compress-pdf",
    endpoint: "/api/v1/optimize/compress",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "level",
        label: "Compression level",
        labelSw: "Kiwango cha kupunguza ukubwa",
        defaultValue: "ebook",
        options: [
          { value: "screen", label: "Smallest size (~72dpi)", labelSw: "Ukubwa mdogo zaidi (~72dpi)" },
          { value: "ebook", label: "Recommended (~150dpi)", labelSw: "Inapendekezwa (~150dpi)" },
          { value: "printer", label: "Best quality (~300dpi)", labelSw: "Ubora wa juu zaidi (~300dpi)" },
        ],
      },
    ],
    resultKind: "file",
    resultFilename: "compressed.pdf",
    submitLabel: "Compress PDF",
    submitLabelSw: "Punguza Ukubwa wa PDF",
    layout: "workspace",
  },
  "repair-pdf": {
    slug: "repair-pdf",
    endpoint: "/api/v1/optimize/repair",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "repaired.pdf",
    submitLabel: "Repair PDF",
    submitLabelSw: "Tengeneza PDF",
    layout: "workspace",
  },
  "ocr-pdf": {
    slug: "ocr-pdf",
    endpoint: "/api/v1/optimize/ocr",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "language",
        label: "Document language",
        labelSw: "Lugha ya hati",
        defaultValue: "eng",
        options: [
          { value: "eng", label: "English", labelSw: "Kiingereza" },
          { value: "swa", label: "Kiswahili", labelSw: "Kiswahili" },
          { value: "fra", label: "French", labelSw: "Kifaransa" },
          { value: "eng+swa", label: "English + Kiswahili", labelSw: "Kiingereza + Kiswahili" },
        ],
      },
    ],
    resultKind: "file",
    resultFilename: "ocr_searchable.pdf",
    submitLabel: "Run OCR",
    submitLabelSw: "Fanya OCR",
    helperNote: "Adds an invisible, searchable text layer over the original scanned pages.",
    helperNoteSw: "Huongeza tabaka la maandishi lisiloonekana linaloweza kutafutwa juu ya kurasa zilizopigwa picha.",
    layout: "workspace",
  },
  "jpg-to-pdf": {
    slug: "jpg-to-pdf",
    endpoint: "/api/v1/convert/image-to-pdf",
    requiresFile: true,
    fileFieldName: "images",
    multiple: true,
    accept: ".jpg,.jpeg,.png,.bmp,.gif,.tiff,.tif,.heic,.webp",
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "orientation",
        label: "Orientation",
        labelSw: "Mwelekeo",
        defaultValue: "auto",
        options: [
          { value: "auto", label: "Auto", labelSw: "Kiotomatiki" },
          { value: "portrait", label: "Portrait", labelSw: "Wima" },
          { value: "landscape", label: "Landscape", labelSw: "Mlalo" },
        ],
      },
      {
        type: "select",
        name: "margin",
        label: "Margin",
        labelSw: "Pambizo",
        defaultValue: "small",
        options: [
          { value: "none", label: "None", labelSw: "Hakuna" },
          { value: "small", label: "Small", labelSw: "Ndogo" },
          { value: "big", label: "Big", labelSw: "Kubwa" },
        ],
      },
      {
        type: "select",
        name: "pageSize",
        label: "Page size",
        labelSw: "Ukubwa wa ukurasa",
        defaultValue: "a4",
        options: [
          { value: "fit", label: "Fit to image", labelSw: "Kulingana na picha" },
          { value: "a4", label: "A4", labelSw: "A4" },
          { value: "letter", label: "Letter", labelSw: "Letter" },
        ],
      },
    ],
    resultKind: "file",
    resultFilename: "images.pdf",
    submitLabel: "Convert to PDF",
    submitLabelSw: "Badilisha kuwa PDF",
    layout: "workspace",
  },
  "word-to-pdf": {
    slug: "word-to-pdf",
    endpoint: "/api/v1/convert/word-to-pdf",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: ".doc,.docx,.odt",
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "converted.pdf",
    submitLabel: "Convert to PDF",
    submitLabelSw: "Badilisha kuwa PDF",
    layout: "workspace",
  },
  "powerpoint-to-pdf": {
    slug: "powerpoint-to-pdf",
    endpoint: "/api/v1/convert/powerpoint-to-pdf",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: ".ppt,.pptx,.odp",
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "converted.pdf",
    submitLabel: "Convert to PDF",
    submitLabelSw: "Badilisha kuwa PDF",
    layout: "workspace",
  },
  "excel-to-pdf": {
    slug: "excel-to-pdf",
    endpoint: "/api/v1/convert/excel-to-pdf",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: ".xls,.xlsx,.csv,.ods",
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "converted.pdf",
    submitLabel: "Convert to PDF",
    submitLabelSw: "Badilisha kuwa PDF",
    layout: "workspace",
  },
  "html-to-pdf": {
    slug: "html-to-pdf",
    endpoint: "/api/v1/convert/html-to-pdf",
    requiresFile: false,
    fileFieldName: "",
    multiple: false,
    accept: "",
    minFiles: 0,
    fields: [
      {
        type: "select",
        name: "inputMode",
        label: "Source",
        labelSw: "Chanzo",
        defaultValue: "url",
        options: [
          { value: "url", label: "Web page URL", labelSw: "Kiungo cha tovuti (URL)" },
          { value: "html", label: "Raw HTML", labelSw: "Msimbo wa HTML" },
        ],
      },
      {
        type: "text",
        name: "url",
        label: "Page URL",
        labelSw: "Kiungo cha ukurasa",
        placeholder: "https://example.com",
        showIf: { field: "inputMode", equals: "url" },
      },
      {
        type: "textarea",
        name: "html",
        label: "HTML source",
        labelSw: "Msimbo wa HTML",
        placeholder: "<html>...</html>",
        showIf: { field: "inputMode", equals: "html" },
      },
      {
        type: "number",
        name: "width",
        label: "Viewport width (px)",
        labelSw: "Upana wa skrini (px)",
        defaultValue: 1024,
        min: 320,
        max: 3000,
      },
      {
        type: "checkbox",
        name: "printBackground",
        label: "Print background colors/images",
        labelSw: "Chapisha rangi/picha za nyuma",
        defaultValue: true,
      },
      {
        type: "select",
        name: "margin",
        label: "Margin",
        labelSw: "Pambizo",
        defaultValue: "small",
        options: [
          { value: "none", label: "None", labelSw: "Hakuna" },
          { value: "small", label: "Small", labelSw: "Ndogo" },
          { value: "big", label: "Big", labelSw: "Kubwa" },
        ],
      },
    ],
    resultKind: "file",
    resultFilename: "webpage.pdf",
    submitLabel: "Convert to PDF",
    submitLabelSw: "Badilisha kuwa PDF",
  },
  "pdf-to-jpg": {
    slug: "pdf-to-jpg",
    endpoint: "/api/v1/convert/pdf-to-jpg",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "format",
        label: "Image format",
        labelSw: "Aina ya picha",
        defaultValue: "jpg",
        options: [
          { value: "jpg", label: "JPG", labelSw: "JPG" },
          { value: "png", label: "PNG", labelSw: "PNG" },
        ],
      },
      {
        type: "select",
        name: "dpi",
        label: "Resolution",
        labelSw: "Ubora wa picha",
        defaultValue: "150",
        options: [
          { value: "150", label: "150 DPI", labelSw: "150 DPI" },
          { value: "300", label: "300 DPI", labelSw: "300 DPI" },
          { value: "600", label: "600 DPI", labelSw: "600 DPI" },
        ],
      },
      {
        type: "checkbox",
        name: "extractEmbeddedImages",
        label: "Extract embedded images instead of rendering pages",
        labelSw: "Toa picha zilizopachikwa badala ya kuchora kurasa",
        defaultValue: false,
      },
    ],
    resultKind: "zip",
    resultFilename: "pdf_images.zip",
    submitLabel: "Convert to Images",
    submitLabelSw: "Badilisha kuwa Picha",
    layout: "workspace",
  },
  "pdf-to-word": {
    slug: "pdf-to-word",
    endpoint: "/api/v1/convert/pdf-to-word",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "checkbox",
        name: "ocrScanned",
        label: "Run OCR on scanned pages first",
        labelSw: "Fanya OCR kwanza kwenye kurasa zilizopigwa picha",
        defaultValue: false,
      },
    ],
    resultKind: "file",
    resultFilename: "converted.docx",
    submitLabel: "Convert to Word",
    submitLabelSw: "Badilisha kuwa Word",
    helperNote: "Extracts text, tables, and layout as editable content — complex designs may need manual cleanup afterward.",
    helperNoteSw:
      "Hutoa maandishi, majedwali, na mpangilio kama maudhui yanayoweza kuhaririwa — miundo tata inaweza kuhitaji usafishaji wa mkono baadaye.",
    layout: "workspace",
  },
  "pdf-to-powerpoint": {
    slug: "pdf-to-powerpoint",
    endpoint: "/api/v1/convert/pdf-to-powerpoint",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "converted.pptx",
    submitLabel: "Convert to PowerPoint",
    submitLabelSw: "Badilisha kuwa PowerPoint",
    helperNote: "Each PDF page becomes one slide, reconstructed from its text and image blocks — not the original slide template.",
    helperNoteSw: "Kila ukurasa wa PDF huwa slaidi moja, iliyojengwa upya kutoka vipande vyake vya maandishi na picha — si muundo asilia wa slaidi.",
    layout: "workspace",
  },
  "pdf-to-excel": {
    slug: "pdf-to-excel",
    endpoint: "/api/v1/convert/pdf-to-excel",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "page-range",
        name: "pages",
        label: "Pages to scan for tables",
        labelSw: "Kurasa za kutafuta majedwali",
        placeholder: LEAVE_BLANK_ALL,
        placeholderSw: LEAVE_BLANK_ALL_SW,
      },
      {
        type: "checkbox",
        name: "ocrScanned",
        label: "Scanned document (use OCR)",
        labelSw: "Hati iliyopigwa picha (tumia OCR)",
        defaultValue: false,
      },
    ],
    resultKind: "file",
    resultFilename: "converted.xlsx",
    submitLabel: "Convert to Excel",
    submitLabelSw: "Badilisha kuwa Excel",
    helperNote: "Detects table structure automatically from ruled/bordered tables. If the PDF is a scan with no selectable text, tick \"Scanned document\" below to read it with OCR first.",
    helperNoteSw: "Hutambua muundo wa jedwali kiotomatiki kwenye majedwali yenye mistari. Kama PDF ni picha ya kupiga picha bila maandishi ya kuchagua, weka alama \"Hati iliyopigwa picha\" hapa chini ili kuisoma kwa OCR kwanza.",
    layout: "workspace",
  },
  "pdf-to-pdfa": {
    slug: "pdf-to-pdfa",
    endpoint: "/api/v1/convert/pdf-to-pdfa",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "standard",
        label: "PDF/A standard",
        labelSw: "Kigezo cha PDF/A",
        defaultValue: "pdfa-2b",
        options: [
          { value: "pdfa-1b", label: "PDF/A-1b (most compatible)", labelSw: "PDF/A-1b (inayoendana zaidi)" },
          { value: "pdfa-2b", label: "PDF/A-2b (recommended)", labelSw: "PDF/A-2b (inapendekezwa)" },
          { value: "pdfa-3b", label: "PDF/A-3b (allows embedded files)", labelSw: "PDF/A-3b (inaruhusu mafaili yaliyowekwa ndani)" },
        ],
      },
    ],
    resultKind: "file",
    resultFilename: "archival.pdf",
    submitLabel: "Convert to PDF/A",
    submitLabelSw: "Badilisha kuwa PDF/A",
    helperNote: "\"b\" (basic) conformance is offered for each part -- \"a\" (fully tagged for accessibility) can't be guaranteed unless the source PDF is already tagged.",
    helperNoteSw: "Kiwango \"b\" (msingi) kinatolewa kwa kila sehemu -- \"a\" (kilichowekwa lebo kikamilifu kwa ufikivu) hakiwezi kuhakikishiwa isipokuwa PDF ya asili tayari ina lebo.",
    layout: "workspace",
  },
  "pdf-to-markdown": {
    slug: "pdf-to-markdown",
    endpoint: "/api/v1/convert/pdf-to-markdown",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [],
    resultKind: "file",
    resultFilename: "converted.md",
    submitLabel: "Convert to Markdown",
    submitLabelSw: "Badilisha kuwa Markdown",
    layout: "workspace",
  },
  "rotate-pdf": {
    slug: "rotate-pdf",
    endpoint: "/api/v1/edit/rotate",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "angle",
        label: "Rotate by",
        labelSw: "Zungusha kwa",
        defaultValue: "90",
        options: [
          { value: "90", label: "90° clockwise", labelSw: "90° kulia" },
          { value: "180", label: "180°", labelSw: "180°" },
          { value: "270", label: "270° clockwise", labelSw: "270° kulia" },
        ],
      },
      {
        type: "page-range",
        name: "pages",
        label: "Pages",
        labelSw: "Kurasa",
        placeholder: LEAVE_BLANK_ALL,
        placeholderSw: LEAVE_BLANK_ALL_SW,
        help: PAGE_RANGE_HELP,
        helpSw: PAGE_RANGE_HELP_SW,
      },
    ],
    resultKind: "file",
    resultFilename: "rotated.pdf",
    submitLabel: "Rotate PDF",
    submitLabelSw: "Zungusha PDF",
    layout: "workspace",
  },
  "add-page-numbers": {
    slug: "add-page-numbers",
    endpoint: "/api/v1/edit/add-page-numbers",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      { type: "text", name: "format", label: "Format", labelSw: "Muundo", defaultValue: "Page {page} of {total}" },
      {
        type: "select",
        name: "position",
        label: "Position",
        labelSw: "Nafasi",
        defaultValue: "bottom-center",
        options: [
          { value: "bottom-center", label: "Bottom center", labelSw: "Chini katikati" },
          { value: "bottom-left", label: "Bottom left", labelSw: "Chini kushoto" },
          { value: "bottom-right", label: "Bottom right", labelSw: "Chini kulia" },
          { value: "top-center", label: "Top center", labelSw: "Juu katikati" },
          { value: "top-left", label: "Top left", labelSw: "Juu kushoto" },
          { value: "top-right", label: "Top right", labelSw: "Juu kulia" },
        ],
      },
      { type: "number", name: "fontSize", label: "Font size", labelSw: "Ukubwa wa herufi", defaultValue: 11, min: 6, max: 48 },
      { type: "text", name: "color", label: "Color (hex)", labelSw: "Rangi (hex)", defaultValue: "#000000" },
      { type: "number", name: "startNumber", label: "Start at", labelSw: "Anzia namba", defaultValue: 1, min: 0 },
      {
        type: "page-range",
        name: "pages",
        label: "Pages",
        labelSw: "Kurasa",
        placeholder: LEAVE_BLANK_ALL,
        placeholderSw: LEAVE_BLANK_ALL_SW,
        help: PAGE_RANGE_HELP,
        helpSw: PAGE_RANGE_HELP_SW,
      },
    ],
    resultKind: "file",
    resultFilename: "numbered.pdf",
    submitLabel: "Add page numbers",
    submitLabelSw: "Ongeza namba za kurasa",
    layout: "workspace",
  },
  "add-watermark": {
    slug: "add-watermark",
    endpoint: "/api/v1/edit/watermark",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      {
        type: "select",
        name: "mode",
        label: "Watermark type",
        labelSw: "Aina ya alama ya maji",
        defaultValue: "text",
        options: [
          { value: "text", label: "Text", labelSw: "Maandishi" },
          { value: "image", label: "Image", labelSw: "Picha" },
        ],
      },
      {
        type: "text",
        name: "text",
        label: "Watermark text",
        labelSw: "Maandishi ya alama ya maji",
        defaultValue: "NSSF CONFIDENTIAL",
        showIf: { field: "mode", equals: "text" },
      },
      { type: "number", name: "opacity", label: "Opacity (%)", labelSw: "Uwazi (%)", defaultValue: 30, min: 0, max: 100 },
      { type: "number", name: "rotation", label: "Rotation (°)", labelSw: "Mzunguko (°)", defaultValue: 45, min: 0, max: 360 },
      {
        type: "select",
        name: "position",
        label: "Position",
        labelSw: "Nafasi",
        defaultValue: "center",
        options: [
          { value: "center", label: "Center", labelSw: "Katikati" },
          { value: "tiled", label: "Tiled", labelSw: "Imesambaa" },
          { value: "top-left", label: "Top left", labelSw: "Juu kushoto" },
          { value: "top-right", label: "Top right", labelSw: "Juu kulia" },
          { value: "bottom-left", label: "Bottom left", labelSw: "Chini kushoto" },
          { value: "bottom-right", label: "Bottom right", labelSw: "Chini kulia" },
        ],
      },
      {
        type: "select",
        name: "layer",
        label: "Layer",
        labelSw: "Tabaka",
        defaultValue: "over",
        options: [
          { value: "over", label: "Over content", labelSw: "Juu ya maudhui" },
          { value: "under", label: "Under content", labelSw: "Chini ya maudhui" },
        ],
      },
      {
        type: "page-range",
        name: "pages",
        label: "Pages",
        labelSw: "Kurasa",
        placeholder: LEAVE_BLANK_ALL,
        placeholderSw: LEAVE_BLANK_ALL_SW,
        help: PAGE_RANGE_HELP,
        helpSw: PAGE_RANGE_HELP_SW,
      },
    ],
    secondaryFile: {
      name: "watermarkImage",
      label: "Watermark image",
      labelSw: "Picha ya alama ya maji",
      accept: ".png,.jpg,.jpeg",
      showIf: { field: "mode", equals: "image" },
    },
    resultKind: "file",
    resultFilename: "watermarked.pdf",
    submitLabel: "Add watermark",
    submitLabelSw: "Ongeza alama ya maji",
    layout: "workspace",
  },
  "crop-pdf": {
    slug: "crop-pdf",
    endpoint: "/api/v1/edit/crop",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      { type: "number", name: "top", label: "Trim from top (pt)", labelSw: "Punguza juu (pt)", defaultValue: 0, min: 0 },
      { type: "number", name: "bottom", label: "Trim from bottom (pt)", labelSw: "Punguza chini (pt)", defaultValue: 0, min: 0 },
      { type: "number", name: "left", label: "Trim from left (pt)", labelSw: "Punguza kushoto (pt)", defaultValue: 0, min: 0 },
      { type: "number", name: "right", label: "Trim from right (pt)", labelSw: "Punguza kulia (pt)", defaultValue: 0, min: 0 },
      {
        type: "page-range",
        name: "pages",
        label: "Pages",
        labelSw: "Kurasa",
        placeholder: LEAVE_BLANK_ALL,
        placeholderSw: LEAVE_BLANK_ALL_SW,
        help: PAGE_RANGE_HELP,
        helpSw: PAGE_RANGE_HELP_SW,
      },
    ],
    resultKind: "file",
    resultFilename: "cropped.pdf",
    submitLabel: "Crop PDF",
    submitLabelSw: "Pogoa PDF",
    helperNote: "Margins are in points (72pt = 1 inch), trimmed from each side of every selected page.",
    helperNoteSw: "Vipimo viko katika points (72pt = inchi 1), vinapunguzwa kila upande wa kurasa zilizochaguliwa.",
    layout: "workspace",
  },
  "unlock-pdf": {
    slug: "unlock-pdf",
    endpoint: "/api/v1/security/unlock",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [{ type: "password", name: "password", label: "Current password", labelSw: "Nenosiri la sasa" }],
    resultKind: "file",
    resultFilename: "unlocked.pdf",
    submitLabel: "Unlock PDF",
    submitLabelSw: "Fungua PDF",
    layout: "workspace",
  },
  "protect-pdf": {
    slug: "protect-pdf",
    endpoint: "/api/v1/security/protect",
    requiresFile: true,
    fileFieldName: "file",
    multiple: false,
    accept: PDF_ACCEPT,
    minFiles: 1,
    fields: [
      { type: "password", name: "userPassword", label: "Password to open (required)", labelSw: "Nenosiri la kufungua (linahitajika)" },
      { type: "password", name: "ownerPassword", label: "Permissions password (optional)", labelSw: "Nenosiri la ruhusa (hiari)" },
      {
        type: "select",
        name: "encryption",
        label: "Encryption",
        labelSw: "Usimbaji fiche",
        defaultValue: "aes256",
        options: [
          { value: "aes128", label: "AES-128", labelSw: "AES-128" },
          { value: "aes256", label: "AES-256", labelSw: "AES-256" },
        ],
      },
      { type: "checkbox", name: "allowPrinting", label: "Allow printing", labelSw: "Ruhusu uchapishaji", defaultValue: true },
      {
        type: "checkbox",
        name: "allowCopying",
        label: "Allow copying text/images",
        labelSw: "Ruhusu kunakili maandishi/picha",
        defaultValue: false,
      },
    ],
    resultKind: "file",
    resultFilename: "protected.pdf",
    submitLabel: "Protect PDF",
    submitLabelSw: "Linda PDF",
    layout: "workspace",
  },
};

export function getToolDefinition(slug: string): ToolDefinition | undefined {
  return TOOL_DEFINITIONS[slug];
}
